// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "apps/backend/prisma/schema.prisma",
  migrations: {
    path: "apps/backend/prisma/migrations",
  },
  datasource: {
    // `prisma generate` к базе не подключается, поэтому отсутствие POSTGRES_URI
    // не должно ломать сборку: раньше env() падал и клиент не генерировался
    // вообще. Пустая строка оставляет внятную ошибку тем командам (migrate,
    // db push), которым адрес действительно нужен.
    url: process.env.POSTGRES_URI ?? "",
  },
});
